### ISSUE TITLE
Integrating the http/2 protocol into the plugin

### ISSUE THREAD

**Issue by kostasoft** [meilisearch/meilisearch-dart#138]
**Description**
Could you add http/2 support to the plugin? I looked at your plugin source code and saw that you are using Dio. on the page of this plugin there is information about using this protocol.

**Basic example**
```
dependencies:
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
```
import 'package:dio/dio.dart';
import 'package:dio_http2_adapter/dio_http2_adapter.dart';

```
  var dio = Dio()
    ..options.baseUrl = 'https://google.com'
    ..interceptors.add(LogInterceptor())
    ..httpClientAdapter = Http2Adapter(
      ConnectionManager(
        idleTimeout: 10000,
        // Ignore bad certificate
        onClientCreate: (_, config) => config.onBadCertificate = (_) => true,
      ),
    );
```

**Comment by brunoocasali** [comment]
Hey, @kostasoft thanks for raising this concern with us!

We have this guide about how you could enable HTTP/2 in your meilisearch server https://docs.meilisearch.com/learn/cookbooks/http2_ssl.html.

I'm not sure about adding this adapter to the client will have the desired effect you want. Do you mean that this client will make the requests using HTTP/2 if we adopt this adapter right? (just a way to force these requests to be made with HTTP/2).

Can you help me understand better what you want/need?

**Comment by brunoocasali** [comment]
I was looking more about the topic in the dio:

I found these two items regarding the fallback to HTTP/1 when HTTP/2 is not available: https://github.com/flutterchina/dio/issues/972 and https://github.com/flutterchina/dio/pull/1425

If the http2 adapter does not support the fallback by default, I cannot add that to the official SDK, because many users will be affected. 

What could be done instead is, to add a way for the user to create their own client and inject that into the client here: https://github.com/meilisearch/meilisearch-dart/blob/main/lib/src/http_request_impl.dart#L8
Like we do here (and other SDK's): https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/MeilisearchClient.cs#L42

**Comment by kostasoft** [comment]
Hello!
Thank you so much for your help.
Thanks to your tip I made changes to three files and was able to add http2 support to the client.
But I really wish I could reassign the default http client when initializing MeiliSearchClient, for example:
```
final customDio = Dio(BaseOptions(...));
_client = MeiliSearchClient(MEILISEARCH_URL, key, httpClient: customDio);
```
