### ISSUE TITLE
Creating a flutter package

### ISSUE THREAD

**Issue by ahmednfwela** [meilisearch/meilisearch-dart#283]
This issue is to track creating a flutter ui kit 

* Related roadmap: https://roadmap.meilisearch.com/c/58-flutter?utm_medium=social&utm_source=portal_share
* Supersedes #281
* Supersedes #278

The new package should be called `meilisearch_ui` and depend on the existing [`meilisearch` package](https://pub.dev/packages/meilisearch)

(similar to firebase's [cloud_firestore](https://pub.dev/packages/cloud_firestore) and  [firebase_ui_firestore](https://pub.dev/packages/firebase_ui_firestore))

There are 2 ways to handle this change

1. create an entirely new repository `meilisearch-flutter` , this is recommended because:
    * So that CI rules don't interfere
    * Separating UI issues from core sdk issues
    * This is how it's done in other sdks, e.g. [meilisearch-js](https://github.com/meilisearch/meilisearch-js) and [instant-meilisearch](https://github.com/meilisearch/instant-meilisearch)
3. transfer the existing `meilisearch-dart` to be monorepo using [melos](https://github.com/invertase/melos)

cc @brunoocasali @alallema

**Comment by ahmednfwela** [comment]
what do you think should be done here ? @brunoocasali 
if you go for option 1, can you create a new repo under meilisearch org please? 👍

**Comment by brunoocasali** [comment]
Hi @ahmednfwela yes, I think option 1 is the best.

I'll create the repo! Plus, since this is not my current priority, I may be late in the reviews, so to avoid blocking your progress, I'll give you the write rights on the repo. Then we can discuss implementation details directly there.

Also, I would like you to take a look here https://github.com/meilisearch/integration-guides/blob/main/resources/build-integration.md. It will be important in this case.

Here is the repo: https://github.com/meilisearch/meilisearch-flutter. I'm making basic changes in the README and other non-tech files required for every meili repo, and I'll commit directly to the main branch.

See you there!

**Comment by brunoocasali** [comment]
By the way @ahmednfwela can you create some issues in the repo, just to make sure we are aligned about the content of this new integration?

**Comment by brunoocasali** [comment]
To everyone interested in this topic, check out the new https://github.com/meilisearch/meilisearch-flutter repository 🎉 

Thanks a lot @ahmednfwela for your genuine interest in making Meilisearch even better ❤️
