### ISSUE TITLE
Enable concurrency for the test suite

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dart#298]
Currently, the test fails when we remove the `--concurrency=1` from the test command.

The idea is to make the tests execute in parallel.

https://github.com/meilisearch/meilisearch-dart/blob/main/.github/workflows/tests.yml#L45

**Comment by ahmednfwela** [comment]
Since dart test has no concept of cross-file testing (unlike c# for example, which can use Fixtures), we have 2 options here:
1. Refactor all tests to be under a single group
2. change the shared `tearDown` function to be test-dependent and only remove indexes/keys used by that specific test instead of a full database cleanup

**Comment by ahmednfwela** [comment]
I went ahead with option 2 and did a full refactor https://github.com/meilisearch/meilisearch-dart/pull/299
