### ISSUE TITLE
Simplify the SDK by removing all the _impl files.

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dart#315]
To be honest I may lack some technical resources to understand it better, but in my POV there is no need to have two files to define a class like: `index.dart` and `index_impl.dart` it seems redundant for me and I can't get the value on having them, but the opposite, I think they make the maintenance harder since those classes were not meant to be extensible I don't see the point on keeping those `_impl` files/classes.

<img width="337" alt="image" src="https://github.com/meilisearch/meilisearch-dart/assets/4116980/0ca6dbae-f52d-4430-91d8-931e9cfc3f10">

I propose to unify the files by removing the abstract classes.

A similar change was done here #185 and I felt it was easier to work with `Task` after that.

CC: @ahmednfwela let me know what do you think about it!

**Comment by ahmednfwela** [comment]
I totally agree, I think this was made to mimic c#'s dependency injection strategy, but in dart it isn't as efficient.

in `HttpRequest`, all the methods are tightly coupled with `dio` since they return `Response<T>`, so it doesn't make sense to have `HttpRequestImpl` when it's the only possible implementation for the base class

and in `MeiliSearchIndex`, a user wouldn't benefit anything from implementing the abstract class, they would rather just extend the existing `MeiliSearchIndexImpl` and override specific methods rather than reinvent the wheel.

similar to what we did in https://github.com/meilisearch/meilisearch-dart/blob/e64dd6368936e06c8e47e1d9c7c6d50aff1e2cd9/test/models/test_client.dart
